// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGpAEGEE8J2noULq9eykD9DKAphj7r0ZQ',
    appId: '1:1036693724270:web:af748bf23f93acc9045a7f',
    messagingSenderId: '1036693724270',
    projectId: 'starrymatch-database',
    authDomain: 'starrymatch-database.firebaseapp.com',
    storageBucket: 'starrymatch-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2qpt2tXhe1lOTmr3Hdpg9W1S49gteTc',
    appId: '1:1036693724270:android:c3d61873c68e94a7045a7f',
    messagingSenderId: '1036693724270',
    projectId: 'starrymatch-database',
    storageBucket: 'starrymatch-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwhsPWg5201oxR7arJdrrNB0jEVygBF-E',
    appId: '1:1036693724270:ios:83305589897401b8045a7f',
    messagingSenderId: '1036693724270',
    projectId: 'starrymatch-database',
    storageBucket: 'starrymatch-database.firebasestorage.app',
    iosBundleId: 'com.example.starryMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwhsPWg5201oxR7arJdrrNB0jEVygBF-E',
    appId: '1:1036693724270:ios:83305589897401b8045a7f',
    messagingSenderId: '1036693724270',
    projectId: 'starrymatch-database',
    storageBucket: 'starrymatch-database.firebasestorage.app',
    iosBundleId: 'com.example.starryMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGpAEGEE8J2noULq9eykD9DKAphj7r0ZQ',
    appId: '1:1036693724270:web:0c36cc5a6c527e56045a7f',
    messagingSenderId: '1036693724270',
    projectId: 'starrymatch-database',
    authDomain: 'starrymatch-database.firebaseapp.com',
    storageBucket: 'starrymatch-database.firebasestorage.app',
  );
}
